### ISSUE TITLE
Architecture document sections (based on arc42)

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/design#32]
[arc42](https://arc42.org/) is a template for writing software architecture documentation, which will help us have at least a guide to writing our report. There are several other sections I still need to add.

- [x] seedcase-project/seedcase-project#67 
- [x] seedcase-project/seedcase-project#79
- [x] seedcase-project/seedcase-project#80
- [x] seedcase-project/seedcase-project#81
- [ ] seedcase-project/design#35
- [ ] seedcase-project/design#34
- [x] seedcase-project/design#26
- [ ] seedcase-project/design#33
- [x] seedcase-project/design#31 
- [ ] seedcase-project/design#29
- [x] seedcase-project/seedcase-project#98
- [ ] seedcase-project/design#28

@rqding and @K-Beicher, use these links to help write these sections.

- https://arc42.org/
- https://www.linkedin.com/pulse/effective-architecture-documentation-arc42-c4-torsten-mosis/
- https://www.innoq.com/en/blog/brief-introduction-to-arc42

Examples:

- https://biking.michael-simons.eu/docs/index.html
- https://hsc.aim42.org/documentation/hsc_arc42.html
